### ISSUE TITLE
Error running Legato

### ISSUE THREAD

**Issue by BilalKoteich** [DOREMUS-ANR/legato#1]
I tried to run "mvn clean install" in the project directory, but I had an error for the following dependencies: 'org.semanticweb.owl', 'fr.inrialpes.exmo', 'fr.inrialpes .exmo.align ', so I added it manually. But when I run the .jar I get the following error: no main manifest attribute, in legato-0.0.1-SNAPSHOT.jar. 
So how to run Legato?

**Comment by kgtodorov** [comment]
Hi. 

It could be that there there are some expired dependencies in the pom file that are not correctly deleted or else that the libraries that have been added manually are not correct. Try these http://www.philippe-fournier-viger.com/spmf/spmf.jar
https://gforge.inria.fr/frs/download.php/zip/10222/alignapi-alignapi-4.9.zip

Feel free to contact the developer @manoach.

**Comment by rtroncy** [comment]
@kgtodorov @manoach Can you perhaps either commit the current libraries you're using for resolving local dependencies or updating the pom file to the newer versions? The [Readme](https://github.com/DOREMUS-ANR/legato/blob/master/README.md) should also be edited to mention the true dependencies.

**Comment by BilalKoteich** [comment]
Hi.

I added the dependencies manually, and I ran 'mvn clean install' without errors.
But when running the .jar file, I got the following error: no main manifest attribute, in legato-0.0.1-SNAPSHOT.jar.
So I modified the pom.xml file and added the following to generate the .jar file with dependencies:

`<plugin>
  			<artifactId>maven-assembly-plugin</artifactId>
  				<configuration>
    				<archive>
      				<manifest>
        				<mainClass>legato.Main</mainClass>
      				</manifest>
    				</archive>
    		<descriptorRefs>
      		<descriptorRef>jar-with-dependencies</descriptorRef>
    		</descriptorRefs>
  		</configuration>
  		<executions>
    		<execution>
      		<id>make-assembly</id> 
      		<phase>package</phase> 
      		<goals>
        		<goal>single</goal>
      		</goals>
    		</execution>
  		</executions>
		</plugin>`

and finally I executed Legato and I had the GUI, but still there are errors.

there is a functional version of Legato?

**Comment by kgtodorov** [comment]
Hi,

Yes! We just went through a major debugging phase of the tool and the updated version of the code will be available within hours. I'll let you know when it is done.

Thanks for your interest in the tool.
Konstantin

**Comment by BilalKoteich** [comment]
ok. 

Thank you :D

**Comment by mvokleber** [comment]
Hello,
I fixed all errors of my knowledge, you can launch Legato without problems.
README file has been completed too, you can consult it to understand how the tool works.

Good afternoon !
Vokleber Marius

**Comment by BilalKoteich** [comment]
Hi. 

i tried to execute 'mvn clean install' to generate the executable jar file, but i had errors, like:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project
 legato: Compilation failure: Compilation failure:
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Align.java:[10,33] package org.semanticweb.owl.align does not exist

[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Align.java:[11,33] package org.semanticweb.owl.align does not exist

[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Align.java:[12,33] package org.semanticweb.owl.align does not exist

[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Align.java:[14,41] package fr.inrialpes.exmo.align.impl.eval does n
ot exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Align.java:[15,38] package fr.inrialpes.exmo.align.parser does not
exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Align.java:[45,54] cannot find symbol
[ERROR] symbol:   class AlignmentException
[ERROR] location: class legato.match.Align
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/HierarchicalClustering.java:[10,59] package ca.pfv.spmf.algorithm
s.clustering.distanceFunctions does not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/HierarchicalClustering.java:[11,36] package ca.pfv.spmf.patterns.
cluster does not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/HierarchicalClustering.java:[12,36] package ca.pfv.spmf.patterns.
cluster does not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/HierarchicalClustering.java:[13,25] package ca.pfv.spmf.tools doe
s not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/HierarchicalClustering.java:[24,22] cannot find symbol
[ERROR] symbol:   class ClusterWithMean
[ERROR] location: class legato.cluster.HierarchicalClustering
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/HierarchicalClustering.java:[33,25] cannot find symbol
[ERROR] symbol:   class DistanceFunction
[ERROR] location: class legato.cluster.HierarchicalClustering
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/HierarchicalClustering.java:[37,111] cannot find symbol
[ERROR] symbol:   class DistanceFunction
[ERROR] location: class legato.cluster.HierarchicalClustering
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/HierarchicalClustering.java:[37,30] cannot find symbol
[ERROR] symbol:   class ClusterWithMean
[ERROR] location: class legato.cluster.HierarchicalClustering
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/utils/PropertyHandler.java:[25,48] package ca.pfv.spmf.algorithms.cluster
ing.dbscan does not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/utils/PropertyHandler.java:[26,36] package ca.pfv.spmf.patterns.cluster d
oes not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/utils/PropertyHandler.java:[27,36] package ca.pfv.spmf.patterns.cluster d
oes not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/Clustering.java:[8,59] package ca.pfv.spmf.algorithms.clustering.
distanceFunctions does not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/Clustering.java:[9,59] package ca.pfv.spmf.algorithms.clustering.
distanceFunctions does not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/Clustering.java:[10,36] package ca.pfv.spmf.patterns.cluster does
 not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/cluster/Clustering.java:[11,36] package ca.pfv.spmf.patterns.cluster does
 not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Matchifier.java:[14,33] package org.semanticweb.owl.align does not
exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Matchifier.java:[15,33] package org.semanticweb.owl.align does not
exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Matchifier.java:[17,59] package ca.pfv.spmf.algorithms.clustering.d
istanceFunctions does not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Matchifier.java:[18,59] package ca.pfv.spmf.algorithms.clustering.d
istanceFunctions does not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Matchifier.java:[19,36] package ca.pfv.spmf.patterns.cluster does n
ot exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Matchifier.java:[20,38] package fr.inrialpes.exmo.align.parser does
 not exist
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Align.java:[51,25] cannot find symbol
[ERROR] symbol:   class AlignmentParser
[ERROR] location: class legato.match.Align
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Align.java:[51,54] cannot find symbol
[ERROR] symbol:   class AlignmentParser
[ERROR] location: class legato.match.Align
[ERROR] /C:/Users/hp/Desktop/legato/src/legato/match/Align.java:[52,25] cannot find symbol
[ERROR] symbol:   class Alignment
[ERROR] location: class legato.match.Align
...

**Comment by mvokleber** [comment]
I don't know currently why these errors occurs. I will try to fix them.
For the moment, Are you try to launch the tool with an IDE like Eclipse ?

Keep in touch !

**Comment by BilalKoteich** [comment]
I tried to launch Legato with Eclipse and it works, but there are an errors during the alignment process (i used the DOREMUS data), i had these errors : 

java.lang.ArrayIndexOutOfBoundsException: 1
	at legato.keys.Sakey.extractKeys(Sakey.java:45)
	at legato.keys.KeysClassifier.getBestKey(KeysClassifier.java:69)
	at legato.match.Matchifier.match(Matchifier.java:122)
	at legato.LEGATO.indexConfig(LEGATO.java:234)
	at legato.LEGATO.buildDocuments(LEGATO.java:179)
	at legato.gui.GUI$7.actionPerformed(GUI.java:330)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ehrhart** [comment]
Hello,

I've made a pull request (#2) that attemps to fix the issues I also had while building with Maven 3.5.2.

@BilalKoteich Could you try using this fork and tell me if it works on your side?

Steps to build:
```
mvn initialize
mvn clean package
```

Steps to run:
```
mvn exec:java
```
